### ISSUE TITLE
Error thrown if an array contains mixed types of primitives and non-primitives

### ISSUE THREAD

**Issue by omgaz** [omgaz/diffler#31]
Due to the recursive nature of diffler if an array contains objects and strings, for example, when the recursion is called obj1 would be an object, but obj2 would be a string. Therefore `key in obj2` would fail.

To resolve this, we'd need to check array types

**Comment by CL0SeY** [comment]
This is also happening when comparing a string to a null.

```
const diffler = require('diffler')
const diff = diffler({ a: null, b: 'things' }, { a: 'more', b: 'things' })
```
results in 
` TypeError: Cannot read property '0' of null`

**Comment by carlosrc** [comment]
Any update on this? Thanks!

**Comment by omgaz** [comment]
I can look sometime this weekend hopefully.

**Comment by carlosrc** [comment]
Thanks for the quick reply!
